/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAiCoachRouteImport } from './routes/_authenticated/ai-coach'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedLearningPlanRouteImport } from './routes/_authenticated/learning-plan'
import { Route as AuthenticatedManageContentRouteImport } from './routes/_authenticated/manage-content'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedReviewApproveRouteImport } from './routes/_authenticated/review-approve'
import { Route as AuthenticatedRoleOverviewRouteImport } from './routes/_authenticated/role-overview'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUploadContentRouteImport } from './routes/_authenticated/upload-content'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiCoachRoute = AuthenticatedAiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningPlanRoute =
  AuthenticatedLearningPlanRouteImport.update({
    id: '/learning-plan',
    path: '/learning-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManageContentRoute =
  AuthenticatedManageContentRouteImport.update({
    id: '/manage-content',
    path: '/manage-content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewApproveRoute =
  AuthenticatedReviewApproveRouteImport.update({
    id: '/review-approve',
    path: '/review-approve',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoleOverviewRoute =
  AuthenticatedRoleOverviewRouteImport.update({
    id: '/role-overview',
    path: '/role-overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUploadContentRoute =
  AuthenticatedUploadContentRouteImport.update({
    id: '/upload-content',
    path: '/upload-content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai-coach': typeof AuthenticatedAiCoachRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/learning-plan': typeof AuthenticatedLearningPlanRoute
  '/manage-content': typeof AuthenticatedManageContentRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/review-approve': typeof AuthenticatedReviewApproveRoute
  '/role-overview': typeof AuthenticatedRoleOverviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload-content': typeof AuthenticatedUploadContentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai-coach': typeof AuthenticatedAiCoachRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/learning-plan': typeof AuthenticatedLearningPlanRoute
  '/manage-content': typeof AuthenticatedManageContentRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/review-approve': typeof AuthenticatedReviewApproveRoute
  '/role-overview': typeof AuthenticatedRoleOverviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/upload-content': typeof AuthenticatedUploadContentRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/': typeof AuthenticatedIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/ai-coach': typeof AuthenticatedAiCoachRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/learning-plan': typeof AuthenticatedLearningPlanRoute
  '/_authenticated/manage-content': typeof AuthenticatedManageContentRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/review-approve': typeof AuthenticatedReviewApproveRoute
  '/_authenticated/role-overview': typeof AuthenticatedRoleOverviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/upload-content': typeof AuthenticatedUploadContentRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai-coach'
    | '/contacts'
    | '/learning-plan'
    | '/manage-content'
    | '/manager'
    | '/resources'
    | '/review-approve'
    | '/role-overview'
    | '/settings'
    | '/upload-content'
    | '/auth/callback'
    | '/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai-coach'
    | '/contacts'
    | '/learning-plan'
    | '/manage-content'
    | '/manager'
    | '/resources'
    | '/review-approve'
    | '/role-overview'
    | '/settings'
    | '/upload-content'
    | '/auth/callback'
    | '/oauth/consent'
    | '/'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/ai-coach'
    | '/_authenticated/contacts'
    | '/_authenticated/learning-plan'
    | '/_authenticated/manage-content'
    | '/_authenticated/manager'
    | '/_authenticated/resources'
    | '/_authenticated/review-approve'
    | '/_authenticated/role-overview'
    | '/_authenticated/settings'
    | '/_authenticated/upload-content'
    | '/auth_/callback'
    | '/oauth/consent'
    | '/_authenticated/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SignupRoute: typeof SignupRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  OauthConsentRoute: typeof OauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-coach': {
      id: '/_authenticated/ai-coach'
      path: '/ai-coach'
      fullPath: '/ai-coach'
      preLoaderRoute: typeof AuthenticatedAiCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning-plan': {
      id: '/_authenticated/learning-plan'
      path: '/learning-plan'
      fullPath: '/learning-plan'
      preLoaderRoute: typeof AuthenticatedLearningPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-content': {
      id: '/_authenticated/manage-content'
      path: '/manage-content'
      fullPath: '/manage-content'
      preLoaderRoute: typeof AuthenticatedManageContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review-approve': {
      id: '/_authenticated/review-approve'
      path: '/review-approve'
      fullPath: '/review-approve'
      preLoaderRoute: typeof AuthenticatedReviewApproveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/role-overview': {
      id: '/_authenticated/role-overview'
      path: '/role-overview'
      fullPath: '/role-overview'
      preLoaderRoute: typeof AuthenticatedRoleOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upload-content': {
      id: '/_authenticated/upload-content'
      path: '/upload-content'
      fullPath: '/upload-content'
      preLoaderRoute: typeof AuthenticatedUploadContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiCoachRoute: typeof AuthenticatedAiCoachRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedLearningPlanRoute: typeof AuthenticatedLearningPlanRoute
  AuthenticatedManageContentRoute: typeof AuthenticatedManageContentRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedReviewApproveRoute: typeof AuthenticatedReviewApproveRoute
  AuthenticatedRoleOverviewRoute: typeof AuthenticatedRoleOverviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUploadContentRoute: typeof AuthenticatedUploadContentRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiCoachRoute: AuthenticatedAiCoachRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedLearningPlanRoute: AuthenticatedLearningPlanRoute,
  AuthenticatedManageContentRoute: AuthenticatedManageContentRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedReviewApproveRoute: AuthenticatedReviewApproveRoute,
  AuthenticatedRoleOverviewRoute: AuthenticatedRoleOverviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUploadContentRoute: AuthenticatedUploadContentRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SignupRoute: SignupRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  OauthConsentRoute: OauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
